### ISSUE TITLE
Add a second data array / second diagram on page

### ISSUE THREAD

**Issue by csongor666** [scanos/php-simple-chart#3]
I would like to represent a second data array (a second temperature sensor ect.)
If i draw a second line, that an empty diagram shows under the first, where all the lines are doubled.
It should be great to use the function as many time as i would like.

**Comment by scanos** [comment]
OK, I will have a look at that, just been busy.

**Comment by scanos** [comment]
You could simply add it as an iframe(deprecated) or html5 object
<object data="https://mysite/mychart......" width="400" height="300" type="text/html">
    Alternative Content
</object>
